-- Your SQL goes here
CREATE TABLE posts (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title NVARCHAR NOT NULL,
    img TEXT NOT NULl,
    body TEXT NOT NULl,
    summary TEXT NOT NULl,
    published BOOLEAN NOT NULL DEFAULT 0 CHECK(published IN (0,1)),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);